### ISSUE TITLE
Issue and Pull request template

### ISSUE THREAD

**Issue by kaustubhgupta** [IndianOpenSourceFoundation/hello-hacktober#10]
# Description
It will be easier for maintainers to have a formal format for raising an issue and evaluating pull requests based on the changes mentioned in the template.

# How to achieve this?
By creating these templates and putting them under .github folder.

# Language
YAML

# Assignee
Self-assignment

**Comment by GouravSardana** [comment]
Nice idea @kaustubhgupta . Go ahead
