### ISSUE TITLE
Invalid Slack Community Link

### ISSUE THREAD

**Issue by crazyuploader** [IndianOpenSourceFoundation/hello-hacktober#16]
# Description
The link given in `README.md` for slack community does not work. 

Attaching screenshot below -

![Screenshot_2020-10-22-13-34-30-977_com android chrome](https://user-images.githubusercontent.com/49350241/96842949-5a103580-146b-11eb-9363-aa592ab2f631.jpg)

# Important Checklist 
-   [x] I have read the contribution guidelines before making this issue.
-   [x] I have verified this issue program is not already implemented.

**Comment by GouravSardana** [comment]
@crazyuploader Thanks for letting us know. I update the link or you can use this by clicking [here](https://join.slack.com/t/iosf-india/shared_invite/zt-is9imrls-YxBT2MJXBu4d7pJEvzAzvw)
If you are still facing an issue, please drop your email in the comment. I will invite you :)
